---
- name: Create or update Fedora VM with extra disk on OpenShift Virtualization
  hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core

  vars:
    namespace: linux-vm
    vm_name: fedora-vm
    image_url: "quay.io/containerdisks/fedora:latest"
    memory: "2Gi"
    cpu_cores: 2

    disk_name: extra-disk
    disk_size: 10Gi
    storage_class: ocs-storagecluster-ceph-rbd-virtualization
    bus: virtio
    access_mode: ReadWriteOnce
    volume_mode: Filesystem

  tasks:

    - name: Check if the VM already exists
      k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ namespace }}"
      register: existing_vm
      failed_when: false

    - name: Create base VM definition
      set_fact:
        base_vm_def:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ namespace }}"
          spec:
            running: true
            template:
              metadata:
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
              spec:
                evictionStrategy: None
                domain:
                  cpu:
                    cores: "{{ cpu_cores }}"
                  resources:
                    requests:
                      memory: "{{ memory }}"
                  devices:
                    disks:
                      - name: containerdisk
                        disk:
                          bus: virtio
                      - name: cloudinitdisk
                        disk:
                          bus: virtio
                volumes:
                  - name: containerdisk
                    containerDisk:
                      image: "{{ image_url }}"
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        user: fedora
                        password: fedora
                        chpasswd: { expire: False }
                        ssh_pwauth: True

    - name: Stop the VM before modifying
      when: existing_vm.resources | length > 0
      k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ namespace }}"
        definition:
          spec:
            running: false

    - name: Wait for VM to fully stop
      when: existing_vm.resources | length > 0
      k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}"
      register: vmi_info
      until: vmi_info.resources | length == 0
      retries: 10
      delay: 5
      ignore_errors: true

    - name: Check if DataVolume exists
      k8s_info:
        api_version: cdi.kubevirt.io/v1beta1
        kind: DataVolume
        name: "{{ disk_name }}"
        namespace: "{{ namespace }}"
      register: dv_check
      failed_when: false

    - name: Create new DataVolume if not present
      when: dv_check.resources | length == 0
      k8s:
        state: present
        definition:
          apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: "{{ disk_name }}"
            namespace: "{{ namespace }}"
          spec:
            pvc:
              accessModes:
                - "{{ access_mode }}"
              resources:
                requests:
                  storage: "{{ disk_size }}"
              volumeMode: "{{ volume_mode }}"
              storageClassName: "{{ storage_class }}"
            source:
              blank: {}

    - name: Get list of existing disk names
      set_fact:
        existing_disk_names: >-
          {{
            existing_vm.resources[0].spec.template.spec.domain.devices.disks
            | map(attribute='name') | list
            if existing_vm.resources | length > 0 else []
          }}

    - name: Get list of existing volume names
      set_fact:
        existing_volume_names: >-
          {{
            existing_vm.resources[0].spec.template.spec.volumes
            | map(attribute='name') | list
            if existing_vm.resources | length > 0 else []
          }}

    - name: Build updated disk list
      set_fact:
        final_disks: >-
          {{
            (existing_vm.resources[0].spec.template.spec.domain.devices.disks
             if existing_vm.resources else base_vm_def.spec.template.spec.domain.devices.disks)
            + ([{ 'name': disk_name, 'disk': { 'bus': bus } }]
               if disk_name not in existing_disk_names else [])
          }}

    - name: Build updated volume list
      set_fact:
        final_volumes: >-
          {{
            (existing_vm.resources[0].spec.template.spec.volumes
             if existing_vm.resources else base_vm_def.spec.template.spec.volumes)
            + ([{ 'name': disk_name, 'dataVolume': { 'name': disk_name } }]
               if disk_name not in existing_volume_names else [])
          }}

    - name: Build final VM definition
      set_fact:
        final_vm_def:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ namespace }}"
            resourceVersion: "{{ existing_vm.resources[0].metadata.resourceVersion if existing_vm.resources else None }}"
          spec:
            running: false
            template:
              metadata:
                labels:
                  kubevirt.io/domain: "{{ vm_name }}"
              spec:
                evictionStrategy: None
                domain:
                  cpu:
                    cores: "{{ cpu_cores }}"
                  resources:
                    requests:
                      memory: "{{ memory }}"
                  devices:
                    disks: "{{ final_disks }}"
                volumes: "{{ final_volumes }}"

    - name: Re-fetch latest VM definition to avoid resourceVersion conflict
      k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ namespace }}"
      register: refreshed_vm
      failed_when: false

    - name: Update resourceVersion in final_vm_def (only if VM exists)
      when: refreshed_vm.resources | length > 0
      set_fact:
        final_vm_def: "{{ final_vm_def | combine({'metadata': {'resourceVersion': refreshed_vm.resources[0].metadata.resourceVersion}}, recursive=True) }}"

    - name: Apply updated VM definition
      k8s:
        state: present
        definition: "{{ final_vm_def }}"

    - name: Start the VM
      k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ namespace }}"
        definition:
          spec:
            running: true
