---
- name: Update RAM of a VM on OpenShift Virtualization (safe and compatible)
  hosts: localhost
  gather_facts: no
  collections:
    - kubernetes.core

  vars:
    namespace: linux-vm
    vm_name: fedora-vm
    new_memory: "4Gi"

  tasks:
    - name: Stop the VM
      k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}"
        definition:
          spec:
            running: false

    - name: Wait for VM to fully stop
      k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}"
      register: vmi_info
      until: vmi_info.resources | length == 0
      retries: 10
      delay: 5
      ignore_errors: true

    - name: Update VM memory (minimal definition, implicit merge patch)
      k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}"
        definition:
          spec:
            template:
              spec:
                domain:
                  resources:
                    requests:
                      memory: "{{ new_memory }}"

    - name: Start the VM
      k8s:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ namespace }}"
        name: "{{ vm_name }}"
        definition:
          spec:
            running: true
